### ISSUE TITLE
Increase write speed by parallelizing with Ensemble HAMT

### ISSUE THREAD

**Issue by abidsikder** [dClimate/py-hamt#9]
Due to the content-immutable assumption of the backing store, it is very difficult to perform multi-threaded writes. In the library, it is currently all effectively single-threaded, since performing multi-threaded operations in memory and then syncing back to the store is very complex.

We can overcome this with an Ensemble HAMT for write-heavy workloads. An EnsembleHAMT will also have the interface of a MutableMapping, allowing for mostly drop-in replacement usage compared to the normal HAMT. 

The algorithm is written below.

1. On initialization of an EnsembleHAMT, create an array of HAMTs, all sharing the same store and configuration options (except for dividing by number of HAMTs the cache size the Ensemble has in total). The number of HAMTs, say `N`, is essentially the parallelization number.
2. For any MutableMapping operations, split the work to the designated HAMT by using the hash of the key.
3. Once all usage is done, merge an EnsembleHAMT into juts one HAMT by merging, in pairs, all of the HAMTs until only one is left.

The basic idea here is to amortise the difficulty of a write-heavy workload into a consolidation step. Although this results in more overall work in terms of operations (a single set of a key becomes approximately $1 + lg(N)$ sets), because the work is parallelized I hypothesize that the amount of time will be much shorter.

Here's a look at the usage pattern from the perspective of the API client.
```python
N = 10 # the parallelization number, approximate speedup
ensemble = EnsembleHAMT(store=IPFSStore(), cache_size=10000000*N) # gives each HAMT the default cache of 10 MB
# large number of set operations
for i in range(0, 2000000):
  ensemble[str(i)] = i
hamt: HAMT = ensemble.consolidate() # floor(lg(N)) merges
```

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the Hamt class to allow working with nodes in memory without immediate serialization. Added a new 'in_memory' flag to control this behavior and adjusted relevant methods.

You can review changes in this commit: https://github.com/mnmnk43434/dClimate-py-hamt-9/commit/98675be649864a022407243d4a662343c6996daa.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
